### ISSUE TITLE
TagCanvas.SetSpeed方法如何使用

### ISSUE THREAD

**Issue by qvxvx** [LucHariman/ng-tagcanvas-example#1]
TagCanvas.SetSpeed('tagid', [0.1, -0.1])；
方法如何使用，设置不起作用

**Comment by LucHariman** [comment]
Hello @qvxvx ,

This method sets the rotation speed of the canvas, it requires the canvas id as a parameter, not a tag id.

More details are available here: http://www.goat1000.com/tagcanvas-functions.php#setspeed
